### PR TITLE
Remove removing @client directive from key generator

### PR DESCRIPTION
**Pull request by ghost**
Hi!

Thanks so much for such a great library!

I ran into a problem, that in my project I have several queries only for local state management, therefore these queries contain only fields with the `@client` directive. And as a result, they have the same `key`, which is `null`, in the `setRequestHandler`method.

So in this PR, I just removed this line as I see no reason to remove the `@client` directive from the generated `key`. Please correct me if I'm wrong.

### CODE REVIEW

**Comment by Mike-Gibson** [comment]
Hi, thanks for using the library and creating this PR.

I personally haven't used client directives yet, but I read the docs to try and understand how they are meant to be used and how they work.

From the docs, it sounds like apollo client looks for client directives, removes them from the query,  passes the query down to the other links and then stitches the result back together. I added tests in a branch [here](https://github.com/Mike-Gibson/mock-apollo-client/blob/feature/client-directives/src/mockClient.integration.test.ts#L62) and it seems to be working that way (the tests pass).

I'm wondering - if the query _only_ contains fields with the `@client` directive, do you even need to call `setRequestHandler`? Won't these queries get resolved via the cache or via client side resolvers? It might be useful if you could provide some code which shows what you're testing and how you're using the library.

**Comment by ghost** [comment]
Thanks for the quick response!

I've created an example [repo](https://github.com/ruslan-petrukhin/mock-apollo-client-example)

My case is this: I have a form with two fields, I save it with the apollo mutation and then navigate to the next screen based on the variable from the apollo state. I want to test that the mutation has been called and that the form navigates to the proper screen.

I would really appreciate it if you can give advice on how to deal with this situation in the best way.

**Comment by Mike-Gibson** [comment]
I had a look, it's an interesting one.

When running the tests in your example repo - I see the warnings apollo gives about resolvers not being defined for the client directives. I guess it's saying there should never be client queries being passed down to the links, hence the warning. This makes me think this PR to include them when computing the key might not be the right approach. 

I'm not sure whether I would mock the client-only queries/mutations - they are important to how the component works and fairly straight forward. Maybe just setting initial state and spying on them is enough?
I made some changes to show how it might work [here](https://github.com/Mike-Gibson/mock-apollo-client-example/commit/5928c7a145b95c77346bced354a7b75a326fac98). 

Of course after the changes I made above, mock-apollo-client isn't actually doing anything - apollo client could just be used instead. 

If you did want to mock out the client queries, I guess you could use a similar approach in the example I made and instead of configuring the initial cache data and then just spying on queries/mutations, configure the jest mock to return the data and not call the actual implementation. Thinking about it, I guess mock-apollo-client could have an option to configure a request handler for a client side query, or have it as an option when adding a request handler.

What do you think? Do you still think it would be useful to have this functionality in mock-apollo-client? I'm happy to think about the API if you still think it would be useful.

**Comment by ghost** [comment]
Thanks so much for the detailed answer!

For the case when queries and mutations have only variables with the `@client` directive, I think your example will work perfectly. But!

Answering your last question, I will say _YES_, this will be useful, because in the future the `saveUser` mutation from the example will be changed to use the values the backend. And when it will be rewritten, having this functionality will be great, since there won't be a lot of changes in the tests.

**Comment by Mike-Gibson** [comment]
Hi @ruslan-petrukhin , I've had a look at this and think I've addressed the issue.

I first tried to update mock-apollo-client to intercept queries and change the behaviour regarding client directives. I thought it would be useful to be able to say "use the mocked response and skip client resolvers" so then it wouldn't matter whether the mock client had been created with or without. Unfortunately the code got very complicated, and I had to monkey-patch one of the Apollo client methods, which I didn't like.

So instead of that, I changed it to be able to specify whether or not the link should include client directives when working out the request key which could be specified when calling `setRequestHandler` in a third optional options parameter.

Then I realised that it's probably much simpler than that. When generating the key for a GraphQL request, we can just generate two keys - one with client directives and one without. (If the one without is null then we don't use it). This way when a query is executed, the handler should be found regardless of whether there are client resolvers or not. The only issue would be when two queries only differ by client directives, but I'm hoping this doesn't happen/is very rare in practice.

I updated your example repo [here](https://github.com/Mike-Gibson/mock-apollo-client-example/tree/updated-mock-apollo-client) and the tests now pass with no changes in the code/tests.

Would be great to get your opinion. If the above sounds OK, I will merge my changes and release a new version.

Cheers!

**Comment by ghost** [comment]
Hi @Mike-Gibson, it's a great job, I really like it!

I have a small question regarding the warning that you mentioned above about client queries being passed down to the links. It's still here. Is it fine and should we just ignore it or maybe something is wrong?

**Comment by Mike-Gibson** [comment]
Thanks for getting back to me.

That's a warning that Apollo client gives (code [here](https://github.com/apollographql/apollo-client/blob/release-2.x/packages/apollo-client/src/core/LocalState.ts#L162) ) because the query has `@client` directives but no client resolvers were configured. To fix the warning, you would have to configure resolvers, but that means that `@client` directives wouldn't be sent down to mock apollo client, and the request handlers wouldn't be called. So I think in this situation you just have to ignore it unfortunately.

**Comment by ghost** [comment]
Thanks, I see.
OK, I think this isn't a big problem :)

So yeah, I think you can merge your PR and make a new release!

**Comment by Mike-Gibson** [comment]
Awesome. 

I've merged #13 and published 0.4.0 to npm which contains this change. Let me know if you run into any problems with the new release.

I'll close this PR. 
Thanks!

**Pull request closed without merging**
