### PR TITLE
Update mockLink.ts

### PR DESCRIPTION
**Pull request by sailod**
make it more clear where the variable is coming from

### CODE REVIEW

**Comment by Mike-Gibson** [comment]
Hi, thanks for contributing. Could you please explain further what you're trying to achieve with this PR?

**Comment by sailod** [comment]
To make the call more explicit, using this helps understand better where it
comes from

**Comment by Mike-Gibson** [comment]
Apologies @sailod , but I still don't understand how this change could make it 'more explicit'. And I'm not sure what you are referring to when you say 'better where it comes from'. Could you give an example of what is more explicit/better to understand after the change? Is it something to do with debugging, stack straces, or just code readability?

I can see the build is failing as the change has introduced a syntax error.

**Comment by Mike-Gibson** [comment]
I'm going to close this as there hasn't been a reply. Feel free to add more info and we can re-open.

**Pull request closed without merging**
